### ISSUE TITLE
Remove the paypal links

### ISSUE THREAD

**Issue by dschaper** [anudeepND/pihole-unbound#8]
Since this guide is almost completely the exact contents of the Pi-hole developer written guide at https://docs.pi-hole.net/guides/unbound/ it's pretty poor taste to add a PayPal link to your copy of our work.

**Comment by vonloschz** [comment]
I took a moment to put side by side these two documentations and no I don't feel like is the "exact contents".
With all respect of your works dschaper and anudeepND.

**Comment by dschaper** [comment]
It's our images, and mostly our text content. Hence my full comment of "almost completely the exact contents." 

Edit: Check the source:

`![screenshot at 2018-04-18](https://docs.pi-hole.net/images/RecursiveResolver.png)`

**Comment by PromoFaux** [comment]
Honestly, @anudeepND, I'd say this is probably not on. Looking back through the commit history of this repo, I can see that the bulk of it was as straight copy paste (commit reference: https://github.com/anudeepND/pihole-unbound/commit/fc50348fd69accea61862655da6aead1011e1029) - 3 Days after the it was added to docs.pi-hole.net

Since then the two documents have diverged slightly, but it remains that slapping a donation link to the bottom of it is in poor taste

![ScreenCap](https://user-images.githubusercontent.com/1998970/103112078-d7fae380-464a-11eb-9c7e-0fba6a8951e9.png)

**Comment by anudeepND** [comment]
At the beginning of the project I used a script to compile the unbound and to make it DoT with letsencrypt etc. but it never made it to the GitHub so the old config stayed. It was not my intention to steal the work, I was lazy to update the things in time. I will remove the entire thing. 
Sorry for my mistakes

**Comment by dschaper** [comment]
Appreciate the update but please remove our images if you don't plan on removing your PayPal link or crediting Pi-hole as the creator of the images.

**Comment by anudeepND** [comment]
@dschaper @PromoFaux  Done. Sorry for plagiarizing you work.
